export const runes = [
  {
    id: 1,
    name: "Bloom",
    type: "Color Rune",
    baseAmountScientific: 7.5e9,
    chance: 7.5e9,
    boosts: [
      { name: "+1Kx Sphere", multiplier: 1000, max: Infinity },
    ],
    exponential: false,
    prefix: "FIRST",
  },
  {
    id: 2,
    name: "Aether",
    type: "Polychrome Rune",
    baseAmountScientific: 1.5e10,
    chance: 1.5e10,
    boosts: [
      { name: "x1 Rune Luck", multiplier: 1.0001, max: 10 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 3,
    name: "Superstar",
    type: "5M Beginner",
    baseAmountScientific: 2.5e10,
    chance: 2.5e10,
    boosts: [
      { name: "x1M Energy", multiplier: 1e6, max: 1e303 },
    ],
    exponential: true,
    prefix: "LIMITED",
  },
  {
    id: 4,
    name: "Vexed",
    type: "Polychrome Rune",
    baseAmountScientific: 5e10,
    chance: 5e10,
    boosts: [
      { name: "x1.05 Tickets", multiplier: 1.05, max: 3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 5,
    name: "Blizzard",
    type: "Arctic Rune",
    baseAmountScientific: 1e11,
    chance: 1e11,
    boosts: [
      { name: "x1.05 Rune Bulk", multiplier: 1.05, max: 3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 6,
    name: "Kingslayer",
    type: "5M Royal",
    baseAmountScientific: 2.5e11,
    chance: 2.5e11,
    boosts: [
      { name: "x25K Orbs", multiplier: 25000, max: 1e303 },
      { name: "x1.25 Rune Luck", multiplier: 1.25, max: 100 },
      { name: "x1.25 Rune Speed", multiplier: 1.25, max: 100 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 7,
    name: "Mystery",
    type: "Basic Rune",
    baseAmountScientific: 1e12,
    chance: 1e12,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 5 },
      { name: "-0.1 RToken Cooldown", multiplier: 1, max: 60 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 8,
    name: "Thorn",
    type: "Nature Rune",
    baseAmountScientific: 1e13,
    chance: 1e13,
    boosts: [
      { name: "x1.05 Rune Speed", multiplier: 1.05, max: 25000 },
      { name: "x2.5 Tickets", multiplier: 2.5, max: 1e10 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 9,
    name: "Divinity",
    type: "5M Royal",
    baseAmountScientific: 7.5e16,
    chance: 7.5e16,
    boosts: [
      { name: "+2 Rune Bulk", multiplier: 1, max: 1e5 },
      { name: "x1 Rune Luck", multiplier: 1, max: 10 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 10,
    name: "Abyssium",
    type: "Nature Rune",
    baseAmountScientific: 1.25e20,
    chance: 1.25e20,
    boosts: [
      { name: "x2.1 Tickets", multiplier: 2.1, max: 10000 },
      { name: "x1.01 Rune Bulk", multiplier: 1.01, max: 100 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 11,
    name: "Prosperity",
    type: "5M Royal",
    baseAmountScientific: 2.5e22,
    chance: 2.5e22,
    boosts: [
      { name: "-1 Chest Chance", multiplier: 2.1, max: 6000 },
      { name: "x1.01 Rune Speed", multiplier: 1.01, max: 100000 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 12,
    name: "Oscillon",
    type: "Polychrome Rune",
    baseAmountScientific: 3.33e27,
    chance: 3.33e27,
    boosts: [
      { name: "x1.02 Rune Luck", multiplier: 1.02, max: 1e6 },
      { name: "^1 Rune Bulk", multiplier: 1, max: 1.3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 13,
    name: "Hyper Finality",
    type: "Basic Rune",
    baseAmountScientific: 7.5e32,
    chance: 7.5e32,
    boosts: [
      { name: "x1 Rune Speed", multiplier: 1, max: 1e12 },
      { name: "Unlock new ticket perk", multiplier: 0, max: 1 },
    ],
    exponential: true,
    prefix: "",
  },
  {
    id: 14,
    name: "Okey Garmin Video Speichern",
    type: "Cryo Rune",
    baseAmountScientific: 1e42,
    chance: 1e42,
    boosts: [
      { name: "x1 Tickets", multiplier: 1, max: 1e51 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 15,
    name: "Gleam",
    type: "Color Rune",
    baseAmountScientific: 1e47,
    chance: 1e47,
    boosts: [
      { name: "x1.01 Rune Speed", multiplier: 1.01, max: 1000 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 10000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 16,
    name: "Shyft",
    type: "Basic Rune",
    baseAmountScientific: 7.5e55,
    chance: 7.5e55,
    boosts: [
      { name: "+1 Walkspeed", multiplier: 1, max: 30 },
      { name: "+7 Rune Bulk", multiplier: 1, max: 500000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 17,
    name: "Overlord",
    type: "5M Beginner",
    baseAmountScientific: 5e58,
    chance: 5e58,
    boosts: [
      { name: "x1.01 Energy", multiplier: 1, max: 1e303 },
      { name: "+24 Rune Bulk", multiplier: 1, max: 1e8 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 18,
    name: "Mirror",
    type: "Arctic Rune",
    baseAmountScientific: 7.5e60,
    chance: 7.5e60,
    boosts: [
      { name: "x1.01 Rune Speed", multiplier: 1, max: 50000 },
      { name: "x1 Rune Speed", multiplier: 1, max: 500000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 19,
    name: "Oblivion",
    type: "Polychrome Rune",
    baseAmountScientific: 5e73,
    chance: 5e73,
    boosts: [
      { name: "x1.02 Rune Bulk", multiplier: 1, max: 50000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 20,
    name: "Immortality",
    type: "5M Royal",
    baseAmountScientific: 2e82,
    chance: 2e82,
    boosts: [
      { name: "x2 Rune Bulk", multiplier: 1, max: 1e9 },
    ],
    exponential: true,
    prefix: "LIMITED",
  },
  {
    id: 21,
    name: "Vanta",
    type: "Color Rune",
    baseAmountScientific: 7e95,
    chance: 7e95,
    boosts: [
      { name: "x2 Rune Speed", multiplier: 1, max: 3e6 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 3 },
      { name: "x2 Tickets", multiplier: 1, max: 1e39 },
    ],
    exponential: true,
    prefix: "",
  },
  {
    id: 22,
    name: "Frostbite",
    type: "Arctic Rune",
    baseAmountScientific: 3e103,
    chance: 3e103,
    boosts: [
      { name: "x1.01 Rune Speed", multiplier: 1, max: 1e5 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 23,
    name: "Odyssey",
    type: "5M Royal",
    baseAmountScientific: 1.5e109,
    chance: 1.5e109,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 10000 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 50 },
      { name: "x1 Rune Speed", multiplier: 1, max: 50 },
    ],
    exponential: true,
    prefix: "LIMITED",
  },
  {
    id: 24,
    name: "Destiny",
    type: "5M Royal",
    baseAmountScientific: 5e121,
    chance: 5e121,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 10000 },
      { name: "x1 Rune Speed", multiplier: 1, max: 250 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 25,
    name: "Squid",
    type: "Nature Rune",
    baseAmountScientific: 5e130,
    chance: 5e130,
    boosts: [
      { name: "x2 Rune Bulk", multiplier: 1, max: 200 },
      { name: "x1.01 Tickets", multiplier: 1, max: 1e12 },
    ],
    exponential: false,
    prefix: "",
  },
  // Добавляй остальные руны сюда...
];
