export const runes = [
  {
    id: 1,
    name: "Bloom",
    type: "Color Rune",
    baseAmountScientific: 7.5e9,
    chance: 7.5e9,
    boosts: [
      { name: "+1Kx Sphere", multiplier: 1000, max: Infinity },
    ],
    exponential: false,
    prefix: "FIRST",
  },
  {
    id: 2,
    name: "Aether",
    type: "Polychrome Rune",
    baseAmountScientific: 1.5e10,
    chance: 1.5e10,
    boosts: [
      { name: "x1 Rune Luck", multiplier: 1.0001, max: 10 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 3,
    name: "Superstar",
    type: "5M Beginner",
    baseAmountScientific: 2.5e10,
    chance: 2.5e10,
    boosts: [
      { name: "x1M Energy", multiplier: 1e6, max: 1e303 },
    ],
    exponential: true,
    prefix: "LIMITED",
  },
  {
    id: 4,
    name: "Vexed",
    type: "Polychrome Rune",
    baseAmountScientific: 5e10,
    chance: 5e10,
    boosts: [
      { name: "x1.05 Tickets", multiplier: 1.05, max: 3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 5,
    name: "Blizzard",
    type: "Arctic Rune",
    baseAmountScientific: 1e11,
    chance: 1e11,
    boosts: [
      { name: "x1.05 Rune Bulk", multiplier: 1.05, max: 3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 6,
    name: "Kingslayer",
    type: "5M Royal",
    baseAmountScientific: 2.5e11,
    chance: 2.5e11,
    boosts: [
      { name: "x25K Orbs", multiplier: 25000, max: 1e303 },
      { name: "x1.25 Rune Luck", multiplier: 1.25, max: 100 },
      { name: "x1.25 Rune Speed", multiplier: 1.25, max: 100 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 7,
    name: "Mystery",
    type: "Basic Rune",
    baseAmountScientific: 1e12,
    chance: 1e12,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 5 },
      { name: "-0.1 RToken Cooldown", multiplier: 1, max: 60 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 8,
    name: "Thorn",
    type: "Nature Rune",
    baseAmountScientific: 1e13,
    chance: 1e13,
    boosts: [
      { name: "x1.05 Rune Speed", multiplier: 1.05, max: 25000 },
      { name: "x2.5 Tickets", multiplier: 2.5, max: 1e10 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 9,
    name: "Divinity",
    type: "5M Royal",
    baseAmountScientific: 7.5e16,
    chance: 7.5e16,
    boosts: [
      { name: "+2 Rune Bulk", multiplier: 1, max: 1e5 },
      { name: "x1 Rune Luck", multiplier: 1, max: 10 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 10,
    name: "Abyssium",
    type: "Nature Rune",
    baseAmountScientific: 1.25e20,
    chance: 1.25e20,
    boosts: [
      { name: "x2.1 Tickets", multiplier: 2.1, max: 10000 },
      { name: "x1.01 Rune Bulk", multiplier: 1.01, max: 100 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 11,
    name: "Prosperity",
    type: "5M Royal",
    baseAmountScientific: 2.5e22,
    chance: 2.5e22,
    boosts: [
      { name: "-1 Chest Chance", multiplier: 2.1, max: 6000 },
      { name: "x1.01 Rune Speed", multiplier: 1.01, max: 100000 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 12,
    name: "Oscillon",
    type: "Polychrome Rune",
    baseAmountScientific: 3.33e27,
    chance: 3.33e27,
    boosts: [
      { name: "x1.02 Rune Luck", multiplier: 1.02, max: 1e6 },
      { name: "^1 Rune Bulk", multiplier: 1, max: 1.3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 13,
    name: "Hyper Finality",
    type: "Basic Rune",
    baseAmountScientific: 7.5e32,
    chance: 7.5e32,
    boosts: [
      { name: "x1 Rune Speed", multiplier: 1, max: 1e12 },
      { name: "Unlock new ticket perk", multiplier: 0, max: 1 },
    ],
    exponential: true,
    prefix: "",
  },
  {
    id: 14,
    name: "Okey Garmin Video Speichern",
    type: "Cryo Rune",
    baseAmountScientific: 1e42,
    chance: 1e42,
    boosts: [
      { name: "x1 Tickets", multiplier: 1, max: 1e51 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 15,
    name: "Gleam",
    type: "Color Rune",
    baseAmountScientific: 1e47,
    chance: 1e47,
    boosts: [
      { name: "x1.01 Rune Speed", multiplier: 1.01, max: 1000 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 10000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 16,
    name: "Shyft",
    type: "Basic Rune",
    baseAmountScientific: 7.5e55,
    chance: 7.5e55,
    boosts: [
      { name: "+1 Walkspeed", multiplier: 1, max: 30 },
      { name: "+7 Rune Bulk", multiplier: 1, max: 500000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 17,
    name: "Overlord",
    type: "5M Beginner",
    baseAmountScientific: 5e58,
    chance: 5e58,
    boosts: [
      { name: "x1.01 Energy", multiplier: 1, max: 1e303 },
      { name: "+24 Rune Bulk", multiplier: 1, max: 1e8 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 18,
    name: "Mirror",
    type: "Arctic Rune",
    baseAmountScientific: 7.5e60,
    chance: 7.5e60,
    boosts: [
      { name: "x1.01 Rune Speed", multiplier: 1, max: 50000 },
      { name: "x1 Rune Speed", multiplier: 1, max: 500000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 19,
    name: "Oblivion",
    type: "Polychrome Rune",
    baseAmountScientific: 5e73,
    chance: 5e73,
    boosts: [
      { name: "x1.02 Rune Bulk", multiplier: 1, max: 50000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 20,
    name: "Immortality",
    type: "5M Royal",
    baseAmountScientific: 2e82,
    chance: 2e82,
    boosts: [
      { name: "x2 Rune Bulk", multiplier: 1, max: 1e9 },
    ],
    exponential: true,
    prefix: "LIMITED",
  },
  {
    id: 21,
    name: "Vanta",
    type: "Color Rune",
    baseAmountScientific: 7e95,
    chance: 7e95,
    boosts: [
      { name: "x2 Rune Speed", multiplier: 1, max: 3e6 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 3 },
      { name: "x2 Tickets", multiplier: 1, max: 1e39 },
    ],
    exponential: true,
    prefix: "",
  },
  {
    id: 22,
    name: "Frostbite",
    type: "Arctic Rune",
    baseAmountScientific: 3e103,
    chance: 3e103,
    boosts: [
      { name: "x1.01 Rune Speed", multiplier: 1, max: 1e5 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 23,
    name: "Odyssey",
    type: "5M Royal",
    baseAmountScientific: 1.5e109,
    chance: 1.5e109,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 10000 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 50 },
      { name: "x1 Rune Speed", multiplier: 1, max: 50 },
    ],
    exponential: true,
    prefix: "LIMITED",
  },
  {
    id: 24,
    name: "Destiny",
    type: "5M Royal",
    baseAmountScientific: 5e121,
    chance: 5e121,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 10000 },
      { name: "x1 Rune Speed", multiplier: 1, max: 250 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 25,
    name: "Squid",
    type: "Nature Rune",
    baseAmountScientific: 5e130,
    chance: 5e130,
    boosts: [
      { name: "x2 Rune Bulk", multiplier: 1, max: 200 },
      { name: "x1.01 Tickets", multiplier: 1, max: 1e12 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 26,
    name: "Array",
    type: "Basic Rune",
    baseAmountScientific: 1e135,
    chance: 1e135,
    boosts: [
      { name: "+3.5K Rune Bulk", multiplier: 1, max: 2.5e10 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 25 },
      { name: "x1 Tickets", multiplier: 1, max: 7.5 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 27,
    name: "Cyclone",
    type: "Nature Rune",
    baseAmountScientific: 2.5e140,
    chance: 2.5e140,
    boosts: [
      { name: "^1.2 Rune Bulk", multiplier: 1, max: 1.2 },
      { name: "x1K Rune Speed", multiplier: 1, max: 1000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 28,
    name: "Stray",
    type: "Cryo Rune",
    baseAmountScientific: 1e160,
    chance: 1e160,
    boosts: [
      { name: "x1 Rune Speed", multiplier: 1, max: 75000 },
      { name: "x1 Tickets", multiplier: 1, max: 1e32 },
    ],
    exponential: true,
    prefix: "",
  },
  {
    id: 29,
    name: "Triarch",
    type: "5M Royal",
    baseAmountScientific: 1.5e165,
    chance: 1.5e165,
    boosts: [
      { name: "x1 Rune Speed", multiplier: 1, max: 75 },
      { name: "x1 Rune Speed", multiplier: 1, max: 500 },
      { name: "x1 Rune Speed", multiplier: 1, max: 50000 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 30,
    name: "Disarray",
    type: "Basic Rune",
    baseAmountScientific: 7.5e174,
    chance: 7.5e174,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 1e12 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 250 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 31,
    name: "Bolt",
    type: "Nature Rune",
    baseAmountScientific: 1.75e182,
    chance: 1.75e182,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 100 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 250 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 32,
    name: "Zephyr",
    type: "Polychrome Rune",
    baseAmountScientific: 5e191,
    chance: 5e191,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 1e6 },
      { name: "x1.01 Rune Speed", multiplier: 1, max: 3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 33,
    name: "Whirl",
    type: "Color Rune",
    baseAmountScientific: 1e204,
    chance: 1e204,
    boosts: [
      { name: "x1 Rune Speed", multiplier: 1, max: 25 },
      { name: "x1 Tickets", multiplier: 1, max: 1000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 34,
    name: "Riptide",
    type: "Nature Rune",
    baseAmountScientific: 1.5e205,
    chance: 1.5e205,
    boosts: [
      { name: "x2 Rune Speed", multiplier: 1, max: "" },
      { name: "x1 Rune Speed", multiplier: 1, max: 500 },
      { name: "x1 Tickets", multiplier: 1, max: 1e34 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 35,
    name: "Cosmic Dust",
    type: "Galactic Rune",
    baseAmountScientific: 1e207,
    chance: 1e207,
    boosts: [
      { name: "x2 Rune Speed", multiplier: 1, max: 2 },
      { name: "x1 Rune Speed", multiplier: 1, max: 500 },
      { name: "x1 Tickets", multiplier: 1, max: 1e34 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 36,
    name: "Star",
    type: "Galactic Rune",
    baseAmountScientific: 2.5e208,
    chance: 2.5e208,
    boosts: [
      { name: "+1 Tickets", multiplier: 1, max: 1e6 },
      { name: "x1 Rune Speed", multiplier: 1, max: 1500 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 37,
    name: "Apex",
    type: "Basic Rune",
    baseAmountScientific: 2.5e212,
    chance: 2.5e212,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 25000 },
      { name: "x1 Rune Speed", multiplier: 1, max: 1000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 38,
    name: "Raze",
    type: "Polychrome Rune",
    baseAmountScientific: 7.5e213,
    chance: 7.5e213,
    boosts: [
      { name: "x500 Rune Bulk", multiplier: 1, max: 500 },
      { name: "x15 Rune Speed", multiplier: 1, max: 15 },
      { name: "x1K Chrome", multiplier: 1, max: 1000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 39,
    name: "Glint",
    type: "Arctic Rune",
    baseAmountScientific: 3.33e219,
    chance: 3.33e219,
    boosts: [
      { name: "x500 Rune Bulk", multiplier: 1, max: 500 },
      { name: "x100 Chrome", multiplier: 1, max: 100 },
      { name: "x1K Chrome", multiplier: 1, max: 1000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 40,
    name: "Buff",
    type: "Cryo Rune",
    baseAmountScientific: 2e225,
    chance: 2e225,
    boosts: [
      { name: "x1 Tickets", multiplier: 1, max: 50000 },
      { name: "x1 Tickets", multiplier: 1, max: 1e6 },
    ],
    exponential: true,
    prefix: "",
  },
  {
    id: 41,
    name: "Constellation",
    type: "Cryo Rune",
    baseAmountScientific: 2.5e225,
    chance: 2.5e225,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 25 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 25 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 42,
    name: "Torrent",
    type: "Nature Rune",
    baseAmountScientific: 2.5e228,
    chance: 2.5e228,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 25 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 25 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 43,
    name: "Sorcerer",
    type: "5M Beginner",
    baseAmountScientific: 1e234,
    chance: 1e234,
    boosts: [
      { name: "x1 Rune Speed", multiplier: 1, max: 100 },
      { name: "x1 Rune Speed", multiplier: 1, max: 1000 },
      { name: "x1 Tickets", multiplier: 1, max: 5e10 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 44,
    name: "Planet",
    type: "Galactic Rune",
    baseAmountScientific: 3.3e238,
    chance: 3.3e238,
    boosts: [
      { name: "+75K Rune Bulk", multiplier: 1, max: 2.5e13 },
      { name: "^1 Rune Bulk", multiplier: 1, max: 1.035 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 45,
    name: "Planet",
    type: "Galactic Rune",
    baseAmountScientific: 3.3e238,
    chance: 3.3e238,
    boosts: [
      { name: "+75K Rune Bulk", multiplier: 1, max: 2.5e13 },
      { name: "^1 Rune Bulk", multiplier: 1, max: 1.035 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 46,
    name: "Onyx",
    type: "Color Rune",
    baseAmountScientific: 3.33e248,
    chance: 3.33e248,
    boosts: [
      { name: "x1 Rune Speed", multiplier: 1, max: 75 },
      { name: "x1 Rune Speed", multiplier: 1, max: 1e5 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 47,
    name: "Strix",
    type: "Basic Rune",
    baseAmountScientific: 2.5e256,
    chance: 2.5e256,
    boosts: [
      { name: "x1.01 Rune Speed", multiplier: 1, max: 3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 48,
    name: "Liberty",
    type: "5M Royal",
    baseAmountScientific: 3.5e256,
    chance: 3.5e256,
    boosts: [
      { name: "x1 Rune Bulk", multiplier: 1, max: 10 },
      { name: "x1 Rune Speed", multiplier: 1, max: 100 },
      { name: "x1 Hail", multiplier: 1, max: 1.25 },
    ],
    exponential: false,
    prefix: "LIMITED",
  },
  {
    id: 49,
    name: "Rocket",
    type: "Galactic Rune",
    baseAmountScientific: 1.5e260,
    chance: 1.5e260,
    boosts: [
      { name: "x1.5 Tickets", multiplier: 1, max: 1e21 },
      { name: "x1 Rune Speed", multiplier: 1, max: 100000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 50,
    name: "Vanguard",
    type: "5M Beginner",
    baseAmountScientific: 6.66e267,
    chance: 6.66e267,
    boosts: [
      { name: "x1 Rune Speed", multiplier: 1, max: 15 },
      { name: "x1 Rune Speed", multiplier: 1, max: 750 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 4000 },
      { name: "x1 Rune Bulk", multiplier: 1, max: 15000 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 51,
    name: "Bozo",
    type: "Cryo Rune",
    baseAmountScientific: 2e294,
    chance: 2e294,
    boosts: [
      { name: "+50 Base Chrome", multiplier: 1, max: 50 },
      { name: "x3 Rune Speed", multiplier: 1, max: 3 },
    ],
    exponential: false,
    prefix: "",
  },
  {
    id: 52,
    name: "Nexus",
    type: "Basic Rune",
    baseAmountScientific: 1e303,
    chance: 1e303,
    boosts: [
      { name: "x1.01 Chrome", multiplier: 1, max: 1e303 },
      { name: "x1.02 Tickets", multiplier: 1, max: 1e303 },
    ],
    exponential: false,
    prefix: "",
  },
  // Добавляй остальные руны сюда...
];
